-- Supabase/Postgres migration for the recycle catalog and richer receipt recycle lines.
-- Apply this before using the admin-managed recycle catalog in customer mode.

CREATE TABLE IF NOT EXISTS public.recyclable_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    material_type VARCHAR(60) NOT NULL,
    unit_label VARCHAR(30) NOT NULL DEFAULT 'piece',
    points_per_unit INT NOT NULL CHECK (points_per_unit > 0),
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_recyclable_items_display_name
ON public.recyclable_items (display_name);

CREATE INDEX IF NOT EXISTS idx_recyclable_items_active_sort
ON public.recyclable_items (is_active, sort_order, display_name);

ALTER TABLE public.receipt_session_lines
    ADD COLUMN IF NOT EXISTS recycle_item_id INT NULL REFERENCES public.recyclable_items(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS recycle_display_name VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS recycle_material_type VARCHAR(60) NULL,
    ADD COLUMN IF NOT EXISTS recycle_unit_label VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS recycle_points_per_unit INT NULL;

ALTER TABLE public.recyclable_items ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'recyclable_items'
          AND policyname = 'Allow all for anon'
    ) THEN
        CREATE POLICY "Allow all for anon"
        ON public.recyclable_items
        FOR ALL
        TO anon
        USING (true)
        WITH CHECK (true);
    END IF;
END
$$;

INSERT INTO public.recyclable_items (
    display_name, material_type, unit_label, points_per_unit, description, is_active, sort_order
)
VALUES
    ('Plastic Bottle', 'PET Plastic', 'bottle', 2, 'Clean PET beverage bottles such as water, juice, or soda bottles.', true, 1),
    ('Aluminum Can', 'Aluminum', 'can', 3, 'Used soda or juice cans made from aluminum.', true, 2),
    ('Glass Bottle', 'Glass', 'bottle', 4, 'Empty glass beverage bottles with no liquid remaining.', true, 3),
    ('Plastic Cup', 'Plastic', 'cup', 1, 'Disposable plastic drink cups that are dry and empty.', true, 4),
    ('Detergent Pouch', 'Flexible Plastic', 'pouch', 1, 'Clean detergent or refill pouches with contents removed.', true, 5),
    ('Tin Can', 'Steel', 'can', 2, 'Food cans made from tin-coated steel, rinsed and empty.', true, 6)
ON CONFLICT (display_name) DO UPDATE
SET
    material_type = EXCLUDED.material_type,
    unit_label = EXCLUDED.unit_label,
    points_per_unit = EXCLUDED.points_per_unit,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order;
