-- Supabase/Postgres migration for session-based receipt history.
-- Apply this before using queued receipt-session sync and receipt history persistence.

CREATE TABLE IF NOT EXISTS public.receipt_sessions (
    receipt_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_sync_id UUID NOT NULL UNIQUE,
    receipt_number VARCHAR(40) NOT NULL,
    machine_id INT NOT NULL REFERENCES public.vending_machines(machine_id) ON DELETE CASCADE,
    session_started_at TIMESTAMPTZ NOT NULL,
    session_ended_at TIMESTAMPTZ NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    amount_paid NUMERIC(10, 2) NOT NULL DEFAULT 0,
    change_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    recycle_points_total INT NOT NULL DEFAULT 0,
    source VARCHAR(16) NOT NULL DEFAULT 'online',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.receipt_session_lines (
    receipt_session_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_session_id BIGINT NOT NULL REFERENCES public.receipt_sessions(receipt_session_id) ON DELETE CASCADE,
    line_order INT NOT NULL,
    entry_type VARCHAR(16) NOT NULL,
    slot_id VARCHAR(10) NULL,
    item_name VARCHAR(100) NULL,
    quantity INT NULL,
    unit_price NUMERIC(10, 2) NULL,
    line_total NUMERIC(10, 2) NULL,
    recycle_material VARCHAR(32) NULL,
    recycle_pieces INT NULL,
    recycle_points INT NULL
);

CREATE INDEX IF NOT EXISTS idx_receipt_sessions_machine_ended
ON public.receipt_sessions (machine_id, session_ended_at DESC);

CREATE INDEX IF NOT EXISTS idx_receipt_session_lines_session_order
ON public.receipt_session_lines (receipt_session_id, line_order);

ALTER TABLE public.receipt_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_session_lines ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'receipt_sessions'
          AND policyname = 'Allow all for anon'
    ) THEN
        CREATE POLICY "Allow all for anon"
        ON public.receipt_sessions
        FOR ALL
        TO anon
        USING (true)
        WITH CHECK (true);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'receipt_session_lines'
          AND policyname = 'Allow all for anon'
    ) THEN
        CREATE POLICY "Allow all for anon"
        ON public.receipt_session_lines
        FOR ALL
        TO anon
        USING (true)
        WITH CHECK (true);
    END IF;
END
$$;
