create table if not exists public.qr_payment_intents (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  token text not null,
  machine_id integer,
  amount numeric(10,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending', 'paid', 'expired', 'cancelled')),
  created_at timestamptz not null default now(),
  scanned_at timestamptz,
  paid_at timestamptz
);

alter table public.qr_payment_intents enable row level security;

create index if not exists idx_qr_payment_intents_reference_token
  on public.qr_payment_intents(reference, token);

create index if not exists idx_qr_payment_intents_created_at
  on public.qr_payment_intents(created_at desc);
